#!/bin/bash

dotnet publish PointsSlip.csproj -c Release -r win-x64 -p:UseAppHost=true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:IncludeAllContentForSelfExtract=true --self-contained true -p:PublishReadyToRunShowWarnings=true -o bin/win-x64
rm -fr bin/Release
rm -fr bin/win-x64/PointsSlip.pdb
rm -fr bin/Debug

set -exuo pipefail

input_file=bin/win-x64/PointsSlip.exe

if [ ! -f "$input_file" ]
then
    echo 'First argument must be path to binary'
    exit 1
fi

# Check that input file is a windows PE (Portable Executable)
if ! ( file "$input_file" | grep -q PE )
then
    echo 'File must be a Portable Executable (PE) file.'
    exit 0
fi

# Check that osslsigncode is installed
if ! command -v osslsigncode >/dev/null 2>&1 ; then
    echo "osslsigncode utility is not present or missing from PATH. Binary cannot be signed."
    exit 1
fi

mv "bin/win-x64/PointsSlip.exe" "bin/win-x64/PointsSlip_unsigned.exe"

osslsigncode sign -certs "Certs/Windows/LGI_SectigoEVCodeSigningCert.cer" -n "Points Slip Calculator" -i "https://github.com/ariplayz/PointsSlipApp/" -t "http://timestamp.sectigo.com" -in "bin/win-x64/PointsSlip_unsigned.exe" -out "bin/win-x64/PointsSlip.exe"