#!/bin/bash

rm -fr bin/osx
rm -fr bin/osx-x64
rm -fr bin/osx-arm64
rm -fr bin/Debug
rm -fr bin/Release
mkdir bin
dotnet publish PointsSlip.csproj -c Release -r osx-x64 -p:UseAppHost=true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:IncludeAllContentForSelfExtract=true --self-contained true -p:PublishReadyToRunShowWarnings=true -o bin/osx-x64
dotnet publish PointsSlip.csproj -c Release -r osx-arm64 -p:UseAppHost=true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:IncludeAllContentForSelfExtract=true --self-contained true -p:PublishReadyToRunShowWarnings=true -o bin/osx-arm64

chmod +x bin/osx-x64/PointsSlip
chmod +x bin/osx-arm64/PointsSlip

mkdir bin/osx
lipo -create -output bin/osx/PointsSlip bin/osx-x64/PointsSlip bin/osx-arm64/PointsSlip

rm -fr bin/Release
rm -fr bin/osx-x64
rm -fr bin/osx-arm64

cp -r Assets/Templates/PointsSlip.app bin/osx/PointsSlip.app
cp Assets/Logos/logo.icns bin/osx/PointsSlip.app/Contents/Resources/logo.icns
cp bin/osx/PointsSlip bin/osx/PointsSlip.app/Contents/MacOS/PointsSlip

productbuild --sign "Developer ID Application: Andrew Cummings (XLA5QQ65S8)" --component bin/osx/PointsSlip.app bin/osx/PointsSlip.pkg

xcrun notarytool submit "bin/osx/PointsSlip.pkg" --apple-id "andrew@artistechendeavors.com" --password "voqy-gjtn-qqzv-jnap" --team-id "XLA5QQ65S8" --wait
xcrun stapler staple "bin/osx/PointsSlip.pkg"

spctl -a -vv "/Volumes/PointsSlip/PointsSlip.app"



# to check the log of the notarization:
# xcrun notarytool log "6406543c-158a-40f5-b541-d844f1719891" --apple-id "andrew@artistechendeavors.com" --password "voqy-gjtn-qqzv-jnap" --team-id "XLA5QQ65S8"
