#!/bin/bash

rm -fr bin
mkdir bin
dotnet publish PointsSlip.csproj -c Release -r osx-x64 -p:UseAppHost=true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:IncludeAllContentForSelfExtract=true --self-contained true -p:PublishReadyToRunShowWarnings=true -o bin/osx-x64
dotnet publish PointsSlip.csproj -c Release -r osx-arm64 -p:UseAppHost=true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:IncludeAllContentForSelfExtract=true --self-contained true -p:PublishReadyToRunShowWarnings=true -o bin/osx-arm64

chmod +x bin/osx-x64/PointsSlip
chmod +x bin/osx-arm64/PointsSlip

codesign --deep --force --verify --verbose --sign "Developer ID Application: Andrew Cummings (XLA5QQ65S8)" --options runtime "bin/osx-x64/PointsSlip"

codesign --deep --force --verify --verbose --sign "Developer ID Application: Andrew Cummings (XLA5QQ65S8)" --options runtime "bin/osx-arm64/PointsSlip"

mkdir bin/osx
lipo -create -output bin/osx/PointsSlip bin/osx-x64/PointsSlip bin/osx-arm64/PointsSlip
chmod +x bin/osx/PointsSlip

codesign --deep --force --verify --verbose --sign "Developer ID Application: Andrew Cummings (XLA5QQ65S8)" "bin/osx/PointsSlip"

codesign -vvv --strict --verbose bin/osx/PointsSlip

rm -fr bin/Release
rm -fr bin/osx-x64
rm -fr bin/osx-arm64

open /Applications/Platypus.app
echo Press Enter to Continue
read

codesign --deep --force --verify --verbose --sign "Developer ID Application: Andrew Cummings (XLA5QQ65S8)" --options runtime "bin/osx/PointsSlip.app"


mkdir bin/osx/PointsSlipDMG
mv bin/osx/PointsSlip.app bin/osx/PointsSlipDMG/PointsSlip.app
create-dmg bin/osx/PointsSlip.dmg bin/osx/PointsSlipDMG/ --volname "Points Slip" --volicon /Users/hauchmahler/Dropbox/Mac/Documents/GitHub/PointsSlipApp/Assets/Logos/logo.icns --window-size 300 500 --background /Users/hauchmahler/Dropbox/Mac/Documents/GitHub/PointsSlipApp/Assets/Images/background.png

xcrun notarytool submit "bin/osx/PointsSlip.dmg" --apple-id "andrew@artistechendeavors.com" --password "voqy-gjtn-qqzv-jnap" --team-id "XLA5QQ65S8" --wait

mount bin/osx/PointsSlip.dmg
spctl -a -vv "/Volumes/PointsSlip/PointsSlip.app"
unmount /Volumes/PointsSlip



# to check the log of the notarization:
# xcrun notarytool log "ad0132a2-1f95-4be2-bc2c-7b877acb6665" --apple-id "andrew@artistechendeavors.com" --password "voqy-gjtn-qqzv-jnap" --team-id "XLA5QQ65S8"